### ISSUE TITLE
node canvas missing Path2D

### ISSUE THREAD

**Issue by hillar** [vladmandic/human#208]
https://github.com/vladmandic/human/blob/7f862d79be5947e478e82a61d2d1aa0e1972d7da/demo/nodejs/process-folder.js#L66

```
/app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:11278
          const pathV = new Path2D(`
                        ^

ReferenceError: Path2D is not defined
    at face (/app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:11278:25)
    at all (/app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:11485:5)
    at Object.all (/app/sk/my-app/node_modules/@vladmandic/human/dist/human.node.js:12946:42)
    at main (/app/sk/my-app/test-human.cjs:84:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
```
temp fix  `human.draw.all(outputCanvas, result,{drawGaze:false});`

ref https://github.com/Automattic/node-canvas/issues/1116

**Comment by vladmandic** [comment]
ah, `node-canvas` does not support SVG as draw item (which is used here to draw an arrow at an angle), great :(  
added check and fixed in main branch.
