### ISSUE TITLE
TypeError while on Android WebView

### ISSUE THREAD

**Issue by Nekronik** [vladmandic/human#277]
**Issue Description**
We have just discovered that for at least Android WebView, some settings need to be enabled for the Local Storage / Indexed DB to be available/work.

- webView.getSettings().[setDomStorageEnabled](https://developer.android.com/reference/android/webkit/WebSettings#setDomStorageEnabled(boolean))(true);
- webView.getSettings().[setDatabaseEnabled](https://developer.android.com/reference/android/webkit/WebSettings#setDatabaseEnabled(boolean))(true);

The Local Storage is accessed assuming it is always available in a web context, which leads to a type error:
```
TypeError: Cannot read properties of null (reading 'length')
  at EC.listModels @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:439153
  at Object.FC @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:441218
  at j$t @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:1672657
  at yRt @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:1712895
  at lOt @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:1843679
  at gFt.load @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:1946538
  at async @ https://identification.scalable.capital/v1/build/p-52c6c72b.entry.js:23:1947869
```
```ts
  constructor() {
    O(K().getBool("IS_BROWSER"), () => "Current environment is not a web browser"), O(typeof window == "undefined" || typeof window.localStorage != "undefined", () => "Current browser does not appear to support localStorage"), this.LS = window.localStorage;
  }
  async listModels() {
    let e = {}, t = qo + Us, n = Us + Rk;
    for (let s = 0; s < this.LS.length; ++s) {
      let r = this.LS.key(s);
      if (r.startsWith(t) && r.endsWith(n)) {
        let a = K_(r);
        e[a] = JSON.parse(this.LS.getItem(r));
      }
```

**Steps to Reproduce**

Run any project using human with this android app [WebView Test](https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=en&gl=US)

**Expected Behavior**

It should check whether Local Storage is available before using it.
A disclaimer would also be helpful in this situation.

**Environment**

- Human library version? 2.8.1
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? esm
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? any
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Android
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? StencilJS

**Comment by vladmandic** [comment]
This is a valid item - I've flagged it as enhancement instead of an issue as `human` was never tested with pure WebView.
I'm traveling right now, so ETA for new release with WebView compatibility is 10-15 days.

**Comment by vladmandic** [comment]
Added initial version of WebView support via <https://github.com/vladmandic/human/commit/12687eadcc0a5f42cc06ead11b8288ad6f6504a3#diff-c360205f487d527338de6d929c0ddd2011e44de18c4ae71b39df1ae6bba8b7d6>

I still need to write a test app - in the meantime, I'd appreciate if you could test it?

**Comment by Nekronik** [comment]
As I linked in the description you can make use of [WebView Test](https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=en&gl=US) which allows you to open any link you want and toggle on and off every single setting exposed from the WebView (including the required permissions).

You can use any of your existing demos through that app, instead of writing anything specifically for it.

**Comment by vladmandic** [comment]
needed one more fix, but seems to be working now...

![image](https://user-images.githubusercontent.com/57876960/178997348-0bcdf4ed-5a93-463a-8cf2-d559deb729c6.png)
