### ISSUE TITLE
Various internal errors

### ISSUE THREAD

**Issue by Nekronik** [vladmandic/human#278]
**Issue Description**

We have also received reports of different errors, that appear to be internal, where we don't know how to fix them nor what they mean.
Any help would be very appreciated.

**1**
```
Error: The implicit shape can't be a fractional number. Got 266 / 3
  at Object.Hy @ https://domain/build/p-2b778b91.entry.js:23:387159
  at Object.jet [as kernelFunc] @ https://domain/build/p-2b778b91.entry.js:23:1234786
  at o @ https://domain/build/p-2b778b91.entry.js:23:421431
  at <anonymous> @ https://domain/build/p-2b778b91.entry.js:23:422286
  at oN.scopedRun @ https://domain/build/p-2b778b91.entry.js:23:419979
  at oN.runKernelFunc @ https://domain/build/p-2b778b91.entry.js:23:422152
  at oN.runKernel @ https://domain/build/p-2b778b91.entry.js:23:420491
  at YE @ https://domain/build/p-2b778b91.entry.js:23:496679
  at reshape__op @ https://domain/build/p-2b778b91.entry.js:23:436119
  at wEt @ https://domain/build/p-2b778b91.entry.js:23:1794153
```
```ts
  }
  if (shapeProd === 0) {
    throw Error(`Cannot infer the missing size in [${shape}] when there are 0 elements`);
  }
  if (size2 % shapeProd !== 0) {
    throw Error(`The implicit shape can't be a fractional number. Got ${size2} / ${shapeProd}`);
  }
  const newShape = shape.slice();
  newShape[implicitIdx] = size2 / shapeProd;
  return newShape;
}
```

**2**
```
Error: The highest priority backend 'wasm' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods
  at hN.get backend [as backend] @ https://domain/build/p-52c6c72b.entry.js:23:403774
  at Z$ @ https://domain/build/p-52c6c72b.entry.js:23:455343
  at mFt @ https://domain/build/p-52c6c72b.entry.js:23:1942221
  at <anonymous> @ https://domain/build/p-52c6c72b.entry.js:23:1943362
  at new Promise @ <anonymous>
  at vFt @ https://domain/build/p-52c6c72b.entry.js:23:1943333
  at gFt.warmup @ https://domain/build/p-52c6c72b.entry.js:23:1947054
  at TFt @ https://domain/build/p-52c6c72b.entry.js:326:937
  at <anonymous> @ https://domain/build/p-52c6c72b.entry.js:326:5433
  at new Promise @ <anonymous>
```

Sadly I don't have more code context for this one.

**3**
```
TypeError: Cannot read properties of undefined (reading 'inputs')
  at UK.get inputs [as inputs] @ https://domain/build/p-52c6c72b.entry.js:23:931328
  at iIt @ https://domain/build/p-52c6c72b.entry.js:23:1739494
  at async lOt @ https://domain/build/p-52c6c72b.entry.js:23:1845975
  at async gFt.load @ https://domain/build/p-52c6c72b.entry.js:23:1946532
  at async @ https://domain/build/p-52c6c72b.entry.js:23:1947869
```

```ts
  }
  get outputNodes() {
    return this.executor.outputNodes;
  }
  get inputs() {
    return this.executor.inputs;
  }
  get outputs() {
    return this.executor.outputs;
  }
  get weights() {
```

**4**
We are also getting this message sometimes `Failed to compile fragment shader.`

**Steps to Reproduce**
We have not identified what produces them, nor found a common pattern.

**Expected Behavior**
No errors

**Environment**

- Human library version? 2.5.8 and 2.8.1
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? esm
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Comment by vladmandic** [comment]
there is a lot going on here, can you provide info what is your platform - where are you running human? which browser and on what hardware?  

most of the errors point to either browser/hardware incompatibility or extremely underpowered device.  

for example:
-  `Failed to compile fragment shader` is a error in WebGL that typically occurs when there is insufficient GPU memory to load models
- `The highest priority backend 'wasm' has not yet been initialized.` is an error that happens when browser says that WebGL is not available and you haven't chosen WASM yourself.
- TypeError: Cannot read properties of undefined (reading 'inputs') is an error that implies that model that is expected to be loaded at that stage never got loaded correctly
  
All 3 of those sound like they have same root cause - **WebGL failures on your device**.  

The only one that's left is:
- `Error: The implicit shape can't be a fractional number. Got 266 / 3` which don't known where it occurs. You've posted code snippet, but that's inside `reshape` function - i need to known where it got called from and for that i need a bit longer backtrace.

**Comment by Nekronik** [comment]
For the related-together errors, human always runs on:
- a mobile device (low and high end)
- any Android version using (Chrome, Chrome WebView, Samsung Internet, Firefox, Mi Browser)
- iOS starting on 14.4 version using (Safari, Chrome, Safari WebView, Firefox)

I have not yet found a way to determine which devices are not going to be able to run human. Do you have any ideas on that regard?

For the `Error: The implicit shape can't be a fractional number. Got 266 / 3`
<details>
  <summary>Everything that I got backtrace-wise</summary>
  
```ts
  }
  if (shapeProd === 0) {
    throw Error(`Cannot infer the missing size in [${shape}] when there are 0 elements`);
  }
  if (size2 % shapeProd !== 0) {
    throw Error(`The implicit shape can't be a fractional number. Got ${size2} / ${shapeProd}`);
  }
  const newShape = shape.slice();
  newShape[implicitIdx] = size2 / shapeProd;
  return newShape;
}
```
```ts
  const { inputs, backend: backend2, attrs } = args;
  const { x } = inputs;
  const { shape } = attrs;
  const webglBackend = backend2;
  const xSize = util_exports.sizeFromShape(x.shape);
  const $shape = util_exports.inferFromImplicitShape(shape, xSize);
  const $xSize = util_exports.sizeFromShape($shape);
  util_exports.assert(xSize === $xSize, () => `The new shape (${$shape}) has ${$xSize} elements and the old shape (${x.shape}) has ${xSize} elements. The new shape and old shape must have the same number of elements.`);
  const xTexData = webglBackend.texData.get(x.dataId);
  if (xTexData.isPacked && !isReshapeFree(x.shape, $shape) && !(xTexData.texture !== null && isReshapeFree(xTexData.shape, $shape))) {
    return packedReshape(x, $shape, webglBackend);
```
```ts
      }
      const kernel = getKernel(kernelName, this.backendName);
      assert(kernel != null, () => `Cannot find registered kernel '${kernelName}' for backend '${this.backendName}'`);
      kernelFunc3 = () => {
        const numDataIdsBefore = this.backend.numDataIds();
        out = kernel.kernelFunc({ inputs: inputs2, attrs: attrs2, backend: this.backend });
        const outInfos = Array.isArray(out) ? out : [out];
        if (this.shouldCheckForMemLeaks()) {
          this.checkKernelForMemLeak(kernelName, numDataIdsBefore, outInfos);
        }
        const outTensors = outInfos.map((outInfo) => {
```
```ts
    const { inputs, attrs } = kernelParams;
    const backwardsFunc = isRegisteredKernelInvocation(kernelParams) ? null : kernelParams.backwardsFunc;
    let kernelProfile;
    this.scopedRun(() => this.state.kernelDepth++, () => this.state.kernelDepth--, () => {
      if (!this.ENV.getBool("DEBUG") && !this.state.profiling) {
        outputs = kernelFunc3();
      } else {
        kernelProfile = this.profiler.profileKernel(kernelOrScopeName, inputs, () => kernelFunc3());
        if (this.ENV.getBool("DEBUG")) {
          this.profiler.logKernelProfile(kernelProfile);
        }
```
```ts
    });
  }
  scopedRun(start, end, f) {
    start();
    try {
      const res = f();
      end();
      return res;
    } catch (ex) {
      end();
      throw ex;
```
```ts
      };
    }
    const { inputs, attrs } = kernelParams;
    const backwardsFunc = isRegisteredKernelInvocation(kernelParams) ? null : kernelParams.backwardsFunc;
    let kernelProfile;
    this.scopedRun(() => this.state.kernelDepth++, () => this.state.kernelDepth--, () => {
      if (!this.ENV.getBool("DEBUG") && !this.state.profiling) {
        outputs = kernelFunc3();
      } else {
        kernelProfile = this.profiler.profileKernel(kernelOrScopeName, inputs, () => kernelFunc3());
        if (this.ENV.getBool("DEBUG")) {
```
```ts
    }
    const hasKernel = getKernel(kernelName, this.backendName) != null;
    if (!hasKernel) {
      throw new Error(`Kernel '${kernelName}' not registered for backend '${this.backendName}'`);
    }
    return this.runKernelFunc({ kernelName, inputs, attrs });
  }
  shouldCheckForMemLeaks() {
    return this.ENV.getBool("IS_TEST");
  }
  checkKernelForMemLeak(kernelName, numDataIdsBefore, outInfos) {
```
```ts
}
function reshape_(x, shape) {
  const $x = convertToTensor(x, "x", "reshape", "string_or_numeric");
  const inputs = { x: $x };
  const attrs = { shape };
  return ENGINE.runKernel(Reshape, inputs, attrs);
}
var reshape = op({ reshape_ });
function avgPool_(x, filterSize, strides2, pad3, dimRoundingMode) {
  const $x = convertToTensor(x, "x", "avgPool", "float32");
  const dilations = 1;
```
```ts
  }
  opName = opName + OP_SCOPE_SUFFIX;
  const f2 = (...args) => {
    ENGINE.startScope(opName);
    try {
      const result = fn(...args);
      if (isPromise(result)) {
        console.error("Cannot return a Promise inside of tidy.");
      }
      ENGINE.endScope(result);
      return result;
```
```ts
        log("face mesh detection requested, but model is not loaded");
    } else {
      const [contours, confidence, contourCoords] = model12.execute(face4.tensor);
      const faceConfidence = await confidence.data();
      face4.faceScore = Math.round(100 * faceConfidence[0]) / 100;
      const coordsReshaped = reshape(contourCoords, [-1, 3]);
      let rawCoords = await coordsReshaped.array();
      dispose([contourCoords, coordsReshaped, confidence, contours]);
      if (face4.faceScore < (((_g = config3.face.detector) == null ? void 0 : _g.minConfidence) || 1)) {
        box.confidence = face4.faceScore;
      } else {
```
</details>

**Comment by vladmandic** [comment]
I haven't tested using less popular browsers such as Samsung Internet or Mi Browser and don't know their capabilities - and unfortunately, browser capabilities vary drastically, so it could be that some don't support WebGL v2.

Regarding which devices are not going to be able to run human - well, it depends. Key factors are:
- Support for WebGL. If its not supported, you need to manually set backend to WASM instead. I can try to add some intelligent fallback in the future.
- If GPU memory is insufficient to compile WebGL code, then there is no automatic fallback possible as capturing that error from a code is a nightmare. So again, you'd need to set backend to WASM or reduce number of modules used by `human`.

Regarding shape error, it happens here: `
```js
const coordsReshaped = reshape(contourCoords, [-1, 3]);
```
but `contourCoords` are results of a model execution, so only way this results in error is if model did not execute correctly - again most likely due to low memory issues. in any case, i'll add some additional checks in that part of the code in the future as well.

**Comment by vladmandic** [comment]
Yes, that reshape error was suspicious from start, but only way that happens is if something within model went wrong - I'll have to dig deeper into that.

If you have any insights on what was being processed at the time of the error?

Anyhow, I'll add some error handling code to capture error as well as attempt to treat it as non-critical. Likely target end of next week as I'm traveling at the moment.

**Comment by vladmandic** [comment]
Nothing strange in either input or in config.
I'll need to dig into this when I'm back.

**Comment by Nekronik** [comment]
I have indeed not received any report for the reshape error on version `2.8.1`, sadly I can't update past `2.5.8` since the next released version introduced the IndexedDB.
Once we can update we will double-check it. I will open a new issue if I spot it again.
Feel free to close the issue or leave it open if you have some work related to it pending.
Thanks :)
