### ISSUE TITLE
Unable to process image

### ISSUE THREAD

**Issue by CayeOficial** [vladmandic/human#362]
**Issue Description**
Error when trying to detect data from image

**Steps to Reproduce**
I create an image from a blob url:
```js
const image = new Image()

const loaded = new Promise((resolve, reject) => {
    image.onload = resolve;
    image.onerror = reject;
});

image.src = blobUrl
//then i wait until the image is loaded
await loaded;

//then i run my custom function to detect data and draw it
await detect(image)
```

The function to detect and draw the data is this:
```js
        const canvas = document.getElementById("image")

        const model = new Human.default({
            backend: 'webgl',
            modelBasePath: '/assets/models/',
            face: { 
              enabled: true,
              emotion: { enabled: false },
              age: { enabled: false },
              gender: { enabled: false },
              iris: { enabled: false },
            },
            body: { enabled: true },
            hand: { enabled: false },
            object: { enabled: false },
            gesture: { enabled: false },
            segmentation: { enabled: false },
            filter: { enabled: false },
        });

        async function detect(image) {
            const result = await model.detect(image);

            const ctx = canvas.getContext('2d');

            ctx.drawImage(image, 0, 0, image.width, image.height);

            for (let face of result.face) {
              ctx.beginPath();
              ctx.rect(face.box.x, face.box.y, face.box.width, face.box.height);
              ctx.strokeStyle = 'red';
              ctx.lineWidth = 2;
              ctx.stroke();
            }
        
            for (let body of result.body) {
              ctx.beginPath();
              ctx.rect(body.box.x, body.box.y, body.box.width, body.box.height);
              ctx.strokeStyle = 'blue';
              ctx.lineWidth = 2;
              ctx.stroke();
            }
        }
 ```

But i get this error in the console
```txt
Uncaught (in promise) Error: The implicit shape can't be a fractional number. Got 266 / 3
    at Object.MS (human.js:7:99948)
    at Object.ye [as kernelFunc] (human.js:1372:1567)
    at o (human.js:11:12267)
    at human.js:11:13067
    at rc.scopedRun (human.js:11:10807)
    at rc.runKernelFunc (human.js:11:12942)
    at rc.runKernel (human.js:11:11311)
    at IT (human.js:16:8830)
    at reshape__op (human.js:11:26225)
    at ry.predict (human.js:4613:96141)
```
**Expected Behavior**
it should work?

- Human library version? -> https://cdnjs.cloudflare.com/ajax/libs/human/2.1.5/human.js
- Built-in demo or custom code? custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- TensorFlow/JS version (if not using bundled module)? 
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? browser -> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 OPR/98.0.0.0
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
can you add `debug: true` to the config object and post console log here as well?

btw, this syntax is suspicious `image.onload = resolve;` as `resolve` object would need to be fixed at the time of entry.
just to be explict, i prefer something like `image.onload = () => resolve()` so method is discovered at the time of the event, not before.
