### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by augchan42** [vladmandic/human#402]
**Issue Description**
npm run build fails
**Steps to Reproduce**
Just do a clone of the repo, and do an npm run build after installing the dev dependencies with npm install --dev
**Expected Behavior**
Build should complete
**Environment**
(.env) hosermage@hosermage-x1:~/projects/human$ npm run build
npm WARN using --force Recommended protections disabled.

> @vladmandic/human@3.1.2 build
> rimraf test/build.log && node build.js

2023-12-06 13:26:32.946558: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-06 13:26:32.983372: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-06 13:26:33 DATA:  Build { name: '@vladmandic/human', version: '3.1.2' }
2023-12-06 13:26:33 INFO:  Application: { name: '@vladmandic/human', version: '3.1.2' }
2023-12-06 13:26:33 INFO:  Environment: { profile: 'production', config: '.build.json', package: 'package.json', tsconfig: true, eslintrc: true, git: true }
2023-12-06 13:26:33 INFO:  Toolchain: { build: '0.9.2', esbuild: '0.17.19', typescript: '5.3.2', typedoc: '0.23.28', eslint: '8.49.0' }
2023-12-06 13:26:33 INFO:  Build: { profile: 'production', steps: [ 'clean', 'compile', 'typings', 'typedoc', 'lint', 'changelog' ] }
2023-12-06 13:26:33 STATE: Clean: { locations: [ 'dist/*', 'types/*', 'typedoc/*' ] }
2023-12-06 13:26:33 STATE: Compile: { name: 'tfjs/browser/version', format: 'esm', platform: 'browser', input: 'tfjs/tf-version.ts', output: 'dist/tfjs.version.js', files: 1, inputBytes: 1289, outputBytes: 399 }
2023-12-06 13:26:33 STATE: Compile: { name: 'tfjs/nodejs/cpu', format: 'cjs', platform: 'node', input: 'tfjs/tf-node.ts', output: 'dist/tfjs.esm.js', files: 2, inputBytes: 607, outputBytes: 994 }
2023-12-06 13:26:33 STATE: Compile: { name: 'human/nodejs/cpu', format: 'cjs', platform: 'node', input: 'src/human.ts', output: 'dist/human.node.js', files: 80, inputBytes: 675985, outputBytes: 320801 }
2023-12-06 13:26:33 STATE: Compile: { name: 'tfjs/nodejs/gpu', format: 'cjs', platform: 'node', input: 'tfjs/tf-node-gpu.ts', output: 'dist/tfjs.esm.js', files: 2, inputBytes: 615, outputBytes: 1002 }
2023-12-06 13:26:33 STATE: Compile: { name: 'human/nodejs/gpu', format: 'cjs', platform: 'node', input: 'src/human.ts', output: 'dist/human.node-gpu.js', files: 80, inputBytes: 675993, outputBytes: 320809 }
2023-12-06 13:26:33 STATE: Compile: { name: 'tfjs/nodejs/wasm', format: 'cjs', platform: 'node', input: 'tfjs/tf-node-wasm.ts', output: 'dist/tfjs.esm.js', files: 2, inputBytes: 703, outputBytes: 2040 }
2023-12-06 13:26:33 STATE: Compile: { name: 'human/nodejs/wasm', format: 'cjs', platform: 'node', input: 'src/human.ts', output: 'dist/human.node-wasm.js', files: 80, inputBytes: 677031, outputBytes: 320921 }
2023-12-06 13:26:33 STATE: Compile: { name: 'tfjs/browser/esm/nobundle', format: 'esm', platform: 'browser', input: 'tfjs/tf-browser.ts', output: 'dist/tfjs.esm.js', files: 2, inputBytes: 1413, outputBytes: 704 }
2023-12-06 13:26:33 STATE: Compile: { name: 'human/browser/esm/nobundle', format: 'esm', platform: 'browser', input: 'src/human.ts', output: 'dist/human.esm-nobundle.js', files: 80, inputBytes: 675695, outputBytes: 319325 }
2023-12-06 13:26:33 STATE: Compile: { name: 'tfjs/browser/esm/bundle', format: 'esm', platform: 'browser', input: 'tfjs/tf-browser.ts', output: 'dist/tfjs.esm.js', files: 10, inputBytes: 1413, outputBytes: 1292236 }
2023-12-06 13:26:33 STATE: Compile: { name: 'human/browser/iife/bundle', format: 'iife', platform: 'browser', input: 'src/human.ts', output: 'dist/human.js', files: 80, inputBytes: 1967227, outputBytes: 1607246 }
2023-12-06 13:26:34 STATE: Compile: { name: 'human/browser/esm/bundle', format: 'esm', platform: 'browser', input: 'src/human.ts', output: 'dist/human.esm.js', files: 80, inputBytes: 1967227, outputBytes: 2103735 }
2023-12-06 13:26:42 STATE: Typings: { input: 'src/human.ts', output: 'types/lib', files: 15 }
/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/types.js:559
            elements = elements?.map((el, i) => new models_1.NamedTupleMember(namedDeclarations[i].name.getText(), !!namedDeclarations[i].questionToken, (0, reflections_1.removeUndefined)(el)));
                                                                                                   ^

TypeError: Cannot read properties of undefined (reading 'name')
    at /home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/types.js:559:100
    at Array.map (<anonymous>)
    at Object.convertType (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/types.js:559:34)
    at convertType (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/types.js:105:34)
    at Object.convertType (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/types.js:123:39)
    at convertType (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/types.js:105:34)
    at Converter.convertType (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/converter.js:93:40)
    at Object.convertProperty (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/symbols.js:366:41)
    at convertSymbol (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/symbols.js:135:41)
    at convertSymbols (/home/hosermage/projects/human/node_modules/@vladmandic/build/node_modules/typedoc/dist/lib/converter/symbols.js:141:9)

Node.js v21.3.0
(.env) hosermage@hosermage-x1:~/projects/human$ npx typedoc --version
npm WARN using --force Recommended protections disabled.

TypeDoc 0.25.1
Using TypeScript 5.3.2 from ./node_modules/typescript/lib

**Comment by augchan42** [comment]
Ok issue is typescript version I was on was 5.3.
Package.json allows this due to ^5.1.6
I downgraded to latest 5.1 (which is 5.16) and was able to complete the build.

I'll amend the package.json and submit as PR

**Comment by vladmandic** [comment]
thanks for the pr. root cause is that `typedoc` isn't compatible with newer typescript, but i'll check what are the latest possible valid versions to use. in the meantime i'll merge your pr as-is.
