### ISSUE TITLE
Library is broken. requestAdapterInfo is deprecated

### ISSUE THREAD

**Issue by anaelshomrai** [vladmandic/human#508]
**Issue Description**
WebGPU requestAdapterInfo seems to be deprecated and replaced with GPUAdapterInfo

**Steps to Reproduce**
Launch the official Human demo, checkout the warning in console 
`hook.js:608 TypeError: e.requestAdapterInfo is not a function
    at Object.factory (human.esm.js:26020:51)
    at async check (human.esm.js:33809:9)
    at async Human.init (human.esm.js:46588:5)
    at async main (index.js:982:5)`

**Expected Behavior**
Update code to use GPUAdapterInfo

**Additional**
It seems like an easy replacement from
`const adapter = await navigator.gpu.requestAdapter();
  this.webgpu.adapter = await adapter?.requestAdapterInfo();
`

To: 
`this.webgpu.adapter = await adapter.info;`

Resources:
1. https://issues.chromium.org/issues/346321149
2. https://developer.mozilla.org/en-US/docs/Web/API/GPUAdapter/requestAdapterInfo
3. https://gpuweb.github.io/gpuweb/#dom-gpuadapter-info
4. https://developer.mozilla.org/en-US/docs/Web/API/GPUAdapterInfo

Thank you !

**Comment by vladmandic** [comment]
why not submit a pr since you already found exact solution?

**Comment by pgg** [comment]
hi vlad, any update on this?
